src/MovieScavengerApp/Models/Actor.cs
using System;

namespace Infusion.MovieScavengerApp.Models
{
    public class Actor
    {
        public string Name { get; set; }
        
        public DateTime BirthDate { get; set; } 
    }
}

src/MovieScavengerApp/Models/Movie.cs
using System;
using System.Collections.Generic;

namespace Infusion.MovieScavengerApp.Models
{
    public class Movie
    {
        public string Title { get; set; }
        
        public DateTime ReleaseDate { get; set; }
        
        public IList<Actor> Cast { get; set; }
    }
}

src/MovieScavengerApp/ViewModels/MovieViewModel.cs
using System;
using System.Collections.Generic;
using Infusion.MovieScavengerApp.Models;

namespace Infusion.MovieScavengerApp.ViewModels
{
    public class MovieViewModel
    {
        public string Title { get; set; }

        public string ReleaseDate { get; set; }

        public string Actors { get; set; }
    }
}

src/MovieScavengerApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Infusion.MovieScavengerApp.Services;
using Infusion.MovieScavengerApp.ViewModels;
using Microsoft.AspNet.Mvc;

namespace Infusion.MovieScavengerApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMoviesService _moviesService;

        public HomeController(IMoviesService moviesService)
        {
            _moviesService = moviesService;
        }

        public IActionResult Index()
        {
            var movieViewModels = new List<MovieViewModel>();
            foreach (var movie in _moviesService.GetMovies())
            {
                movieViewModels.Add(new MovieViewModel
                {
                    Title = movie.Title,
                    ReleaseDate = movie.ReleaseDate.ToString("d"),
                    // Extra task: separate each actor with new line and add BirthDate information for each actor
                    Actors = movie.Cast != null ? string.Join(", ", movie.Cast.Select(t => t.Name)) : null
                });
            }

            return View(movieViewModels);
        }
    }
}

src/MovieScavengerApp/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Infusion.MovieScavengerApp.Services;
using Infusion.MovieScavengerApp.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Infusion.MovieScavengerApp.Controllers
{
    public class MovieController : Controller
    {
        // GET: /<controller>/

        private IMoviesService _moviesService;
        
        public MovieController(IMoviesService moviesService) { _moviesService = moviesService; } // *** działa bo w serviceconfig dodaliśmy tą linijkę
                
        public IActionResult Index()
        {
            return View();
        }

        // DONE: Snippet 4
        [HttpPost]
        public IActionResult AddMovie(string title, string releaseDate)
        {
            // Extra task: implement input validation
            // DONE: insert snippet 5
            _moviesService.AddMovie(new Movie
            {
                Title = title,
                ReleaseDate = DateTime.Parse(releaseDate)
            });
            return Content("Movie Added"); // Extra task: redirect to Home/Index instead
        }
    }
}

src/MovieScavengerApp/Views/Home/Index.cshtml
@model IList<Infusion.MovieScavengerApp.ViewModels.MovieViewModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Movie Scavenger - Home</title>
</head>
<body>
<div>
    <h1>Movie List</h1>
    <table>
        <thead>
        <tr><th>Title</th><th>Release Date</th><th>Cast</th></tr>
        </thead>
        <tbody>
            @foreach (var movie in Model)
            {
                <tr><td>@movie.Title</td><td>@movie.ReleaseDate</td><td>@movie.Actors</td></tr>
            }
        </tbody>
    </table>

    @* DONE: insert snippet 3 *@
    @Html.ActionLink("Add Another Movie", "Index", "Movie")
    
</div>
</body>
</html>

src/MovieScavengerApp/Views/Movie/Index.cshtml
@model Infusion.MovieScavengerApp.ViewModels.MovieViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Movie Scavenger - Add Movie</title>
</head>
<body>
<div>
    <h1>Add Movie</h1>
    @using (var form = Html.BeginForm("AddMovie", "Movie"))
    {
        @* Extra task 4: add support for entering actors/cast *@
        <table>
            <thead>
            <tr><th>Title</th><th>Release Date</th></tr>
            </thead>
            <tbody>
            <tr><td><input type="text" name="title"/></td><td><input type="text" name="releaseDate"/></td></tr>
            </tbody>
        </table>
        
        <input type="submit" title="Submit" />
    }
</div>
</body>
</html>